apiVersion: v1
kind: Service
metadata:
  name: doc-processor-service
spec:
  type: NodePort
  selector:
    app: doc-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
